### ISSUE TITLE
How to use Cohere command R+ model or Together AI's models?

### ISSUE THREAD

**Issue by svk-cu-nlp** [bracesproul/gen-ui-python#4]
model = ChatOpenAI(model="gpt-4o", temperature=0, streaming=True) this is the default one. How to make use other models like Cohere or Together AI's models?

**Comment by bracesproul** [comment]
@svk-cu-nlp you'll have to switch that class implementation with the class you'd rather use.
e.g
```python
model = ChatCohere(...)
```
