### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by dejankocic** [bracesproul/gen-ui-python#5]
Hello, could you please fix this

![image](https://github.com/bracesproul/gen-ui-python/assets/6128938/784a95a6-e411-4105-8bce-8d89a5f1c6be)

**Comment by lakshyaag** [comment]
Your URL is incorrect. Try this:

`git clone https://github.com/bracesproul/gen-ui-python.git`

**Comment by bracesproul** [comment]
Looks like I had a typo in the readme url. Fixed it here https://github.com/bracesproul/gen-ui-python/pull/7

**Comment by dejankocic** [comment]
Thx, much appreciated.
